	baseURL = 'https://theoffcuts.org'
	languageCode = 'en-us'
	title = 'The Offcuts | Halle Winkler'
	description = 'The Offcuts | Halle Winkler'
	images = ['/images/gyro2.png']
[params.shareButtons]
	size = "small"
	networks = ["twitter", "linkedin"]
	icon = "solid"
  [Social]
  twitter = "HalleWinkler"
  [twitter]
	card = "summary_large_image"
	site = "@HalleWinkler"
	creator = "@HalleWinkler"
	image = "/images/gyro2.png"