	baseURL = 'https://theoffcuts.org'
	languageCode = 'en-us'
	title = 'The Offcuts | Halle Winkler'
	description = 'The Offcuts | Halle Winkler'
	images = ['/images/cmio/TechnicalDifficulties.jpg']

    date_format = "02 Jan 2006"
[params.shareButtons]
	size = "small"
	networks = ["linkedin"]
	icon = "solid"
  [Social]
  twitter = "HalleWinkler"
  [twitter]
	card = "summary_large_image"
	site = "@HalleWinkler"
	creator = "@HalleWinkler"
	image = "/images/gyro2.png"
